# Generated by Django 5.2.17 on 2026-09-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ledger.category')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
    ]
