/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["config_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_csrf_probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Csrf Probe */
        post: operations["config_api_csrf_probe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["ledger_api_list_accounts"];
        put?: never;
        /** Create Account */
        post: operations["ledger_api_create_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Account */
        patch: operations["ledger_api_patch_account"];
        trace?: never;
    };
    "/api/accounts/{account_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Account */
        post: operations["ledger_api_reconcile_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["ledger_api_list_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transaction Defaults */
        get: operations["ledger_api_transaction_defaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["ledger_api_list_transactions"];
        put?: never;
        /** Create Transaction Route */
        post: operations["ledger_api_create_transaction_route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["ledger_api_delete_transaction"];
        options?: never;
        head?: never;
        /** Patch Transaction */
        patch: operations["ledger_api_patch_transaction"];
        trace?: never;
    };
    "/api/import/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["imports_api_list_profiles"];
        put?: never;
        /** Create Profile */
        post: operations["imports_api_create_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Profile */
        delete: operations["imports_api_delete_profile"];
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["imports_api_patch_profile"];
        trace?: never;
    };
    "/api/import/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["imports_api_list_batches"];
        put?: never;
        /** Upload Batch */
        post: operations["imports_api_upload_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["imports_api_get_batch"];
        put?: never;
        post?: never;
        /** Discard */
        delete: operations["imports_api_discard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/batches/{batch_id}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Batch Rows */
        patch: operations["imports_api_patch_batch_rows"];
        trace?: never;
    };
    "/api/import/batches/{batch_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["imports_api_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["insights_api_get_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Budget Progress */
        get: operations["budgets_api_list_budget_progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Budget */
        put: operations["budgets_api_put_budget"];
        post?: never;
        /** Delete Budget */
        delete: operations["budgets_api_delete_budget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountWithBalanceOut */
        AccountWithBalanceOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Opening Balance */
            opening_balance: string;
            /** Balance */
            balance: string;
        };
        /** AccountIn */
        AccountIn: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Opening Balance
             * @default 0.00
             */
            opening_balance: string;
        };
        /** AccountPatchIn */
        AccountPatchIn: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Opening Balance */
            opening_balance?: string | null;
        };
        /** ReconcileOut */
        ReconcileOut: {
            transaction: components["schemas"]["TransactionOut"] | null;
            /** Balance */
            balance: string;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: string;
            /** Description */
            description: string;
            /** Kind */
            kind: string;
            /** Account Id */
            account_id: number;
            /** Category Id */
            category_id: number | null;
            /** Destination Account Id */
            destination_account_id: number | null;
        };
        /** ReconcileIn */
        ReconcileIn: {
            /** Actual Balance */
            actual_balance: string;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Colour */
            colour: string;
            /** Side */
            side: string;
            /** Protected Role */
            protected_role: string | null;
        };
        /** ManualEntryDefaultsOut */
        ManualEntryDefaultsOut: {
            /** Account Id */
            account_id: number;
            /** Expense Category Id */
            expense_category_id: number;
            /** Income Category Id */
            income_category_id: number;
        };
        /** TransactionIn */
        TransactionIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "expense" | "income" | "transfer";
            /** Account Id */
            account_id: number;
            /** Category Id */
            category_id?: number | null;
            /** Destination Account Id */
            destination_account_id?: number | null;
        };
        /** TransactionPatchIn */
        TransactionPatchIn: {
            /** Date */
            date?: string | null;
            /** Amount */
            amount?: string | null;
            /** Description */
            description?: string | null;
            /** Kind */
            kind?: ("expense" | "income" | "transfer") | null;
            /** Account Id */
            account_id?: number | null;
            /** Category Id */
            category_id?: number | null;
            /** Destination Account Id */
            destination_account_id?: number | null;
        };
        /** MappingProfileOut */
        MappingProfileOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Date Column */
            date_column: string;
            /** Amount Column */
            amount_column: string | null;
            /** Debit Column */
            debit_column: string | null;
            /** Credit Column */
            credit_column: string | null;
            /** Description Column */
            description_column: string;
            /** Counterparty Column */
            counterparty_column: string | null;
            /** Date Format */
            date_format: string;
            /** Decimal Separator */
            decimal_separator: string;
            /** Encoding */
            encoding: string;
        };
        /** MappingProfileIn */
        MappingProfileIn: {
            /** Name */
            name: string;
            /** Date Column */
            date_column: string;
            /** Amount Column */
            amount_column?: string | null;
            /** Debit Column */
            debit_column?: string | null;
            /** Credit Column */
            credit_column?: string | null;
            /** Description Column */
            description_column: string;
            /** Counterparty Column */
            counterparty_column?: string | null;
            /** Date Format */
            date_format: string;
            /** Decimal Separator */
            decimal_separator: string;
            /**
             * Encoding
             * @default utf-8
             */
            encoding: string;
        };
        /** MappingProfilePatchIn */
        MappingProfilePatchIn: {
            /** Name */
            name?: string | null;
            /** Date Column */
            date_column?: string | null;
            /** Amount Column */
            amount_column?: string | null;
            /** Debit Column */
            debit_column?: string | null;
            /** Credit Column */
            credit_column?: string | null;
            /** Description Column */
            description_column?: string | null;
            /** Counterparty Column */
            counterparty_column?: string | null;
            /** Date Format */
            date_format?: string | null;
            /** Decimal Separator */
            decimal_separator?: string | null;
            /** Encoding */
            encoding?: string | null;
        };
        /** PendingBatchDetailOut */
        PendingBatchDetailOut: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Profile Id */
            profile_id: number;
            /** Source Filename */
            source_filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Row Count */
            row_count: number;
            /** Unparsable Count */
            unparsable_count: number;
            /** Duplicate Count */
            duplicate_count: number;
            /** Groups */
            groups: components["schemas"]["VendorGroupOut"][];
            /** Ungrouped Rows */
            ungrouped_rows: components["schemas"]["PendingRowOut"][];
            /** Unparsable Rows */
            unparsable_rows: components["schemas"]["PendingRowOut"][];
        };
        /** PendingRowOut */
        PendingRowOut: {
            /** Id */
            id: number;
            /** Row Number */
            row_number: number;
            /** Raw Line */
            raw_line: string;
            /** Parse Error */
            parse_error: string | null;
            /** Date */
            date: string | null;
            /** Amount */
            amount?: string | null;
            /** Description */
            description: string;
            /** Counterparty */
            counterparty: string | null;
            /** Kind */
            kind: string;
            /** Category Id */
            category_id: number | null;
            /** Destination Account Id */
            destination_account_id: number | null;
            /** Is Duplicate */
            is_duplicate: boolean;
            /** Include */
            include: boolean;
        };
        /** VendorGroupOut */
        VendorGroupOut: {
            /** Counterparty */
            counterparty: string;
            /** Rows */
            rows: components["schemas"]["PendingRowOut"][];
        };
        /** PendingBatchSummaryOut */
        PendingBatchSummaryOut: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Profile Id */
            profile_id: number;
            /** Source Filename */
            source_filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Row Count */
            row_count: number;
            /** Unparsable Count */
            unparsable_count: number;
            /** Duplicate Count */
            duplicate_count: number;
        };
        /** PendingRowPatchIn */
        PendingRowPatchIn: {
            /** Row Id */
            row_id: number;
            /** Category Id */
            category_id?: number | null;
            /** Kind */
            kind?: string | null;
            /** Destination Account Id */
            destination_account_id?: number | null;
            /** Include */
            include?: boolean | null;
        };
        /** ConfirmOut */
        ConfirmOut: {
            /** Created */
            created: number;
        };
        /** BreakdownItemOut */
        BreakdownItemOut: {
            category: components["schemas"]["CategoryOut"];
            /** Amount */
            amount: string;
            /** Share */
            share: string;
        };
        /** BudgetProgressItemOut */
        BudgetProgressItemOut: {
            category: components["schemas"]["CategoryOut"];
            /** Monthly Limit */
            monthly_limit: string;
            /** Spent */
            spent: string;
            /** Over Limit */
            over_limit: boolean;
        };
        /** BudgetsSectionOut */
        BudgetsSectionOut: {
            /** Month */
            month: string;
            /** Items */
            items: components["schemas"]["BudgetProgressItemOut"][];
        };
        /** InsightsOut */
        InsightsOut: {
            /** Spending Over Time */
            spending_over_time: components["schemas"]["SpendingBucketOut"][];
            /** Expense Breakdown */
            expense_breakdown: components["schemas"]["BreakdownItemOut"][];
            /** Income Breakdown */
            income_breakdown: components["schemas"]["BreakdownItemOut"][];
            budgets: components["schemas"]["BudgetsSectionOut"];
        };
        /** SpendingBucketOut */
        SpendingBucketOut: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Amount */
            amount: string;
        };
        /** BudgetOut */
        BudgetOut: {
            category: components["schemas"]["CategoryOut"];
            /** Monthly Limit */
            monthly_limit: string;
        };
        /** BudgetLimitIn */
        BudgetLimitIn: {
            /** Monthly Limit */
            monthly_limit: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    config_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    config_api_csrf_probe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_api_list_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalanceOut"][];
                };
            };
        };
    };
    ledger_api_create_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalanceOut"];
                };
            };
        };
    };
    ledger_api_patch_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalanceOut"];
                };
            };
        };
    };
    ledger_api_reconcile_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconcileIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileOut"];
                };
            };
        };
    };
    ledger_api_list_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    ledger_api_transaction_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualEntryDefaultsOut"];
                };
            };
        };
    };
    ledger_api_list_transactions: {
        parameters: {
            query?: {
                account_id?: number | null;
                category_id?: number | null;
                kind?: string | null;
                from?: string | null;
                to?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
        };
    };
    ledger_api_create_transaction_route: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
        };
    };
    ledger_api_delete_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_api_patch_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
        };
    };
    imports_api_list_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingProfileOut"][];
                };
            };
        };
    };
    imports_api_create_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingProfileIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingProfileOut"];
                };
            };
        };
    };
    imports_api_delete_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imports_api_patch_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingProfilePatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingProfileOut"];
                };
            };
        };
    };
    imports_api_list_batches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingBatchSummaryOut"][];
                };
            };
        };
    };
    imports_api_upload_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Account Id */
                    account_id: number;
                    /** Profile Id */
                    profile_id: number;
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingBatchDetailOut"];
                };
            };
        };
    };
    imports_api_get_batch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingBatchDetailOut"];
                };
            };
        };
    };
    imports_api_discard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imports_api_patch_batch_rows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PendingRowPatchIn"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingBatchDetailOut"];
                };
            };
        };
    };
    imports_api_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmOut"];
                };
            };
        };
    };
    insights_api_get_insights: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsOut"];
                };
            };
        };
    };
    budgets_api_list_budget_progress: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetProgressItemOut"][];
                };
            };
        };
    };
    budgets_api_put_budget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetLimitIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
        };
    };
    budgets_api_delete_budget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
