# Generated by Django 5.2.17 on 2026-09-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_column', models.CharField(max_length=200)),
                ('amount_column', models.CharField(blank=True, max_length=200, null=True)),
                ('debit_column', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_column', models.CharField(blank=True, max_length=200, null=True)),
                ('description_column', models.CharField(max_length=200)),
                ('counterparty_column', models.CharField(blank=True, max_length=200, null=True)),
                ('date_format', models.CharField(max_length=50)),
                ('decimal_separator', models.CharField(choices=[('.', '.'), (',', ',')], max_length=1)),
                ('encoding', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount_column__isnull', False), ('debit_column__isnull', True), ('credit_column__isnull', True)), models.Q(('amount_column__isnull', True), ('debit_column__isnull', False), ('credit_column__isnull', False)), _connector='OR'), name='mapping_profile_amount_layout')],
            },
        ),
        migrations.CreateModel(
            name='PendingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='ledger.account')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='imports.mappingprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_line', models.TextField()),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('counterparty', models.CharField(blank=True, max_length=500, null=True)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], max_length=10)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('include', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.pendingbatch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_rows', to='ledger.category')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_transfer_rows', to='ledger.account')),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_row_number_per_batch')],
            },
        ),
    ]
