# Generated by Django 5.2.17 on 2026-09-28 11:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit card'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('colour', models.CharField(max_length=7)),
                ('side', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('protected_role', models.CharField(blank=True, choices=[('uncategorised', 'Uncategorised'), ('unaccounted', 'Unaccounted')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['side', 'name'],
                'constraints': [models.UniqueConstraint(fields=('side', 'name'), name='unique_category_name_per_side'), models.UniqueConstraint(condition=models.Q(('protected_role__isnull', False)), fields=('side', 'protected_role'), name='unique_protected_role_per_side')],
            },
        ),
        migrations.CreateModel(
            name='ManualEntryPreference',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_manual_entry_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.category')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='ledger.account')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='transaction_amount_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('destination_account__isnull', False), ('kind', 'transfer'), models.Q(('destination_account', models.F('account')), _negated=True)), models.Q(models.Q(('kind', 'transfer'), _negated=True), ('category__isnull', False), ('destination_account__isnull', True)), _connector='OR'), name='transaction_kind_shape')],
            },
        ),
    ]
